config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'shoes#index'
  resources :companies
  resources :comments

  resources :categories

  resources :shoes

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :shoe
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :shoe
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
acts_as_commentable
mount_uploader :cover, ::ImageUploader
belongs_to :category
belongs_to :company

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_all_categories, :authenticate_user!
  private  
  def get_all_categories
    @categories = Category.all
  end
    def get_all_companies
    @companies = Company.active
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @all_shoes = Shoe.all
  end

  def show
    @category_shoes = @category.shoe
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :active)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to book_path(@comment.commentable) }
      format.js
    end
    
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :commentable_type, :commentable_id).merge(user_id: current_user.id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @companies = Company.all
    respond_with(@companies)
  end

  def show
    respond_with(@company)
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name, :active)
    end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
def notify_friend 
      @shoe = Shoe.find(params[:id]) 
      Notifier.email_friend(@shoe, params[:name],      params[:email]).deliver 

      redirect_to @shoe, :notice => "Successfully sent a       message to your friend" 
  respond_to :html
end

  def index
    @shoes = Shoe.all
    
  end

  def show
    @all_comments = @shoe.comments
    @new_comment = @shoe.comments.build
    #respond_with(@shoe)
  end

  def new
    @shoe = Shoe.new
    respond_with(@shoe)
  end

  def edit
  end

  def create
    @shoe = Shoe.new(shoe_params)
    @shoe.save
    respond_with(@shoe)
  end

  def update
    @shoe.update(shoe_params)
    respond_with(@shoe)
  end

  def destroy
    @shoe.destroy
    respond_with(@shoe)
  end

  private
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    def shoe_params
      params.require(:shoe).permit(:name, :description, :cover, :price, :category_id, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.active %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render "common/shoe_list", shoes: @category_shoes%>

app/views/comments/_comment_item.html.erb
<li><%= comment.user.email%>: <%= comment.comment%></li>

app/views/comments/create.js.erb
console.log("comment ", "<%= @comment.comment%>");
$("#book-comments").append("<%= escape_javascript(render "comment_item", comment: @comment)%>")
$("#comment_comment").val("")

app/views/common/_shoe_list.html.erb
  <% shoes.each do |shoe| %>

<table width="242" height="262"  border="0" cellpadding="0" cellspacing="0" class="Pr">
            <tr>
              <td valign="top" class="BodyBkg"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td height="50" align="center"><%= shoe.name %><br>
                    <%= shoe.category.try(:name)%></td>
                  </tr>
                <tr>
                  <td height="142" align="center"><a href=<%=shoe_path(shoe)%> > <img src= <%= shoe.cover_url(:normal) %>  alt="" width="217" height="112" border="0"></a></td>
                  </tr>
                <tr>
                  <td height="34" align="center">starting at <span class="style1"><%= shoe.price %></span></td>
                  </tr>
                <tr>
                  <td align="center"><table width="210"  border="0" cellspacing="0" cellpadding="0">
                    <tr align="center">
                      <td height="35"><a href=<%=shoe_path(shoe)%> ><img src= <%= asset_path("bt1.jpg")%> alt="" width="101" height="29" border="0"></a></td>
                      <td><img src= <%= asset_path("bt2.jpg")%> alt="" width="91" height="29" border="0"></a></td>
                    </tr>
                  </table></td>
                </tr>
              </table></td>
            </tr>
          </table>
          <%end%>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.active %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @company.active %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_footer.html.erb
<tr>
                  
                </tr>
              </table></td>
            </tr>
          </table>		  
		  
		  </td>
      </tr>
    </table></td>
  </tr>
<tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td align="center"><a href="http://www.templatesfreelance.com/"><img src= <%= asset_path("footer.gif")%> alt="" width="920" height="4" border="0"></a></td>
  </tr>
  <tr>
    <td height="60" align="center"><a href="http://www.templatesfreelance.com/">Home</a> | <a href="http://www.templatesfreelance.com/">News</a> | <a href="http://www.templatesfreelance.com/">Reviews</a> | <a href="http://www.templatesfreelance.com/">How-To's</a> | <a href="http://www.templatesfreelance.com/">Downloads</a> | <a href="http://www.templatesfreelance.com/">Shop &amp; Compare</a> | <a href="http://www.templatesfreelance.com/">Apps</a> | <a href="http://www.templatesfreelance.com/">Business Center</a> | <a href="http://www.templatesfreelance.com/">FAQ</a> | <a href="http://www.templatesfreelance.com/">Contact Us</a><br>
    TemplatesFreeLance.com &copy; copyright 2012 - <a href="http://www.templatesfreelance.com/">Web Page Templates </a></td>
  </tr>

app/views/layouts/_side_banner.html.erb
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><a href="http://www.templatesfreelance.com/"><img src= <%= asset_path("rightBaner.jpg") %> alt="" width="192" height="334" border="0"></a></td>
            </tr>
          </table></td>

app/views/layouts/_sidebar.html.erb
 <tr>
    <td height="20">&nbsp;</td>
  </tr>
  <tr>
    <td><table width="920"  border="0" cellspacing="0" cellpadding="0">
      <tr align="left" valign="top">
        <td width="192" height="479"><table width="192"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="38" class="topMenu LeftMenuHeader" ><a href= <%= categories_path %>>All Categories</a></td>
          </tr>
        </table>          
          <table width="100%"  border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="216" valign="top">
                <div class="RightMenu">
                  <ul>
                    
                      <% @categories.each do |cat|%>
                                                  <li > 
                    <a href= <%= category_path(cat)%>><%=cat.name%></a></li>
                        <%end%>
    
                  </ul>
              </div></td>
            </tr>
          </table>

app/views/layouts/_top_banner.html.erb
<td width="727">
		
		<table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><a href="http://www.templatesfreelance.com/"><img src= <%= asset_path("bigBaner.gif") %> alt="" width="727" height="312" border="0"></a></td>
          </tr>
          <tr>
            <td height="38" class="topMenu LeftMenuHeader" >Featured Products<a href="http://www.templatesfreelance.com"><img src= <%= asset_path("spacer.gif")%> alt="" width="10" height="10" border="0"></a></td>
          </tr>
        </table>
		

app/views/layouts/_top_menu.html.erb
<tr>
    <td height="38" class="menu">
	
	<div class="menuLs">
				<ul>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Home</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">News</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Reviews</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">How-To's </a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Downloads</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Shop & Compare</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Apps</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Business Center</a></li>
				<li><a href="http://www.templatesfreelance.com/" id="WhiteColor">FAQ</a></li>
				</ul>
	</div>	</td>
  </tr>

app/views/layouts/_top_nav.html.erb
<%if user_signed_in?%>
<tr>
    <td height="25">&nbsp;</td>
  </tr>
  <tr>
    <td height="77" class="header"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="28%" align="left"><a href="http://www.templatesfreelance.com/"><img src= <%= asset_path("logo.jpg") %> alt="" width="262" height="77" border="0"></a></td>
        <td width="72%" align="right">

		<b>Welcome <%= current_user.email%></b>&nbsp;&nbsp;
		<%= link_to "Log out", destroy_user_session_path, method: :delete%> &nbsp;&nbsp;
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		
		</td>
      </tr>
    </table></td>
  </tr>
  <%else%>
  <tr>
    <td height="25">&nbsp;</td>
  </tr>
  <tr>
    <td height="77" class="header"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="28%" align="left"><a href="http://www.templatesfreelance.com/"><img src= <%= asset_path("logo.jpg") %> alt="" width="262" height="77" border="0"></a></td>
        <td width="72%" align="right">
    <a href="/users/sign_in">Login</a>&nbsp;&nbsp;
    <a href="/users/sign_up">Registration</a> &nbsp;&nbsp;
    <a href="#">Contact Us</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    
    </td>
      </tr>
    </table></td>
  </tr>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
 <title><%= content_for?(:title) ? yield(:title) : "ShoeStore"%></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' =>true %>
 <%= csrf_meta_tags %>
</head>

<body>
<table width="920"  border="0" cellspacing="0" cellpadding="0" align="center">
  <%= render "layouts/top_nav"%>
  <%= render "layouts/top_menu"%>
  <%= render "layouts/sidebar"%>
   <%= render "layouts/side_banner"%>
 <%= render "layouts/top_banner"%>
          
        <%=yield %>
		
		
          
                
  <%= render "layouts/footer"%>
</table>
</body>
</html>

app/views/notifier/email_friend.html.erb
<h1>Notifier#email_friend</h1>

<p>
  <%= @greeting %>, find me in app/views/notifier/email_friend.html.erb
</p>

app/views/notifier/email_friend.text.erb
Notifier#email_friend

<%= @greeting %>, find me in app/views/notifier/email_friend.text.erb

app/views/shoes/_form.html.erb
<%= form_for(@shoe) do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
  <%= f.label :category %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="field">
  <%= f.label :company %>
  <%= f.collection_select(:company_id, Company.all, :id, :name) %>
  </div>
  <div class="field">
  <%= f.label :cover %>
  <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/_notify_friend.html.erb
<%= form_tag(notify_friend_shoe_path(@shoe), :id => 'notify_friend_form',  
:style => 'display:none') do %> 

  <div class="field"> 
    <%= label_tag :name, 'Your name' %><br /> 
    <%= text_field_tag :name %> 
  </div> 

  <div class="field"> 
    <%= label_tag :email, "Your friend's email" %><br /> 
    <%= text_field_tag :email %> 
  </div> 

  <div class="actions"> 
    <%= submit_tag 'Send' %> or 
    <%= link_to 'Cancel', '#', :onclick => "$('#notify_friend_form').slideUp()" %> 
  </div> 
<% end %> 

app/views/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
  <% @shoes.each do |shoe| %>

<table width="242" height="262"  border="0" cellpadding="0" cellspacing="0" class="Pr">
            <tr>
              <td valign="top" class="BodyBkg"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td height="50" align="center"><%= shoe.name %> </td>
                  </tr>
                <tr>
                  <td height="142" align="center"><a href=<%=shoe_path(shoe)%> > <img src= <%= shoe.cover_url(:normal) %>  alt="" width="217" height="112" border="0"></a></td>
                  </tr>
                <tr>
                  <td height="34" align="center">starting at <span class="style1"><%= shoe.price %> VND</span></td>
                  </tr>
                <tr>
                  <td align="center"><table width="210"  border="0" cellspacing="0" cellpadding="0">
                    <tr align="center">
                      <td height="35"><a href=<%=shoe_path(shoe)%> ><img src= <%= asset_path("bt1.jpg")%> alt="" width="101" height="29" border="0"></a></td>
                      <td><img src= <%= asset_path("bt2.jpg")%> alt="" width="91" height="29" border="0"></a></td>
                    </tr>
                  </table></td>
                </tr>
              </table></td>
            </tr>
          </table>
          <%end%>
<%= link_to 'New Shoe', new_shoe_path %>

app/views/shoes/new.html.erb
<h1>New shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Cover:</strong>
  <img src=<%= @shoe.cover_url() %> />
  
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %>
</p>

<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>
<div>
  <ul id = "book-comments">
    <%@all_comments.each do |c|%>
      <%unless c.new_record? %>
        <%= render "comments/comment_item", comment: c%>
      <%end%>
    <%end%>
  </ul>
</div>


<%= form_for(@new_comment, remote: true) do |f|%>
  <%= f.text_area :comment%>
  <%= f.hidden_field :commentable_type%>
  <%= f.hidden_field :commentable_id%>
  <br/>
  <%= f.submit%>
<%end%>

<%= javascript_tag do%>
  console.log("hello word");
<% end %>
<%= link_to 'Email a friend', '#',  
:onclick => "$('#notify_friend_form').slideDown()" %> 